modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="modflared"
version="${version}"
displayName="Modflared"
logoFile="icon.png"
authors="HttpRafa, Contributers"
description='''Automatically connects you to a Cloudflare tunnel without having to install cloudflared separately.'''

[[dependencies.modflared]]
modId="forge"
mandatory = true
versionRange="[36,)"
ordering="NONE"
side="CLIENT"

[[dependencies.modflared]]
modId="minecraft"
mandatory = true
versionRange="[${minecraft_version},)"
ordering="NONE"
side="CLIENT"
