org.gradle.jvmargs=-Xmx2G
org.gradle.java.home=/usr/lib/jvm/java-8-openjdk
org.gradle.daemon=true

minecraft_version=1.12.2
forge_version=14.23.5.2847
mcp_mappings=stable_39

mod_id=modflared
mod_name=Modflared
mod_license=MIT
mod_version=1.12.2-legacy.1
mod_group_id=dev.httxrafa.modflared
mod_authors=HttpRafa, Contributors
mod_description=Automatically connects you to a Cloudflare tunnel without having to install cloudflared separately.
