# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Game Properties
minecraft_version=1.21.4
yarn_version=1.21.4+build.2
yarn_mappings_patch=1.21+build.4
enabled_platforms=fabric,neoforge

# Mod Properties
archives_base_name=modflared
mod_version=1.2.2
maven_group=de.rafael
mod_minecraft_version=1.21.4

# Loader Properties
fabric_loader_version=0.16.9
fabric_api_version=0.114.0+1.21.4
neoforge_version=21.4.47-beta

# Modrinth Properties
modrinth_project_id=modflared

# Curseforge Properties
curseforge_project_id=997330

# Publish Properties
mod_version_type=release