name: build_publish
on:
  pull_request:
  push:
    paths:
      - fabric/**
      - neoforge/**
      - common/**
      - build.gradle
      - gradle.properties
jobs:
  build_publish:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: upload to modrinth
        if: github.ref == 'refs/heads/multi/latest'
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          GITHUB_EVENT_RAW_PATH: ${{ github.event_path }}